### ISSUE TITLE
List of models in the backoffice is not always sorted

### ISSUE THREAD

**Issue by jlopezr** [RouteInjector/route-injector#14]
It would be nice that the order of the models in the left panel can be control. Or alphabetically sorted. Or, at least, that all times keep the same order ;)

**Comment by jlopezr** [comment]
It would be nice that the order of the models in the left panel can be control. Or alphabetically sorted. Or, at least, that all times keep the same order ;)

**Comment by jlopezr** [comment]
@Abaena sorted at least the first level on the menu.

**Comment by Abaena** [comment]
Solved on ri-backoffice version 2.1.16
