### ISSUE TITLE
Image Injector backed only in a string

### ISSUE THREAD

**Issue by jlopezr** [RouteInjector/route-injector#9]
Current image injector is complex and uses multiple fields to store an image. The idea is to have one simple image injector that stores the relative URL/path in one string.

**Comment by GerardSoleCa** [comment]
Implementing a Gallery to perform uploads and assigns for NON-Image models. They will be backed by strings.

Support three types:
* Images
* Files
* Videos

**Comment by GerardSoleCa** [comment]
Gallery is fully implemented. Single Item Gallery is also implemented.

* Check for undefined creation of directories
* Do not push a dir creation if dir path is empty
* When creating a dir from Backoffice, model form is submited. This shouldn't happen.
